import glob
Import('env')

# Loop over libraries, building each
this_env=env.Clone()
this_env.PrependUnique(LIBS="libbdxRecoExt") 
this_env.PrependUnique(LIBS="libbdxReco")
this_env.PrependUnique(LIBS='JANA')


this_env.AppendUnique(LIBS='cmsg')
this_env.AppendUnique(LIBS='cmsgxx')
this_env.AppendUnique(LIBS='cmsgRegex')
this_env.AppendUnique(LIBS='RootSpy')
  

progs=['bdxReco']
for prog in progs:
    src =Glob(prog+'/*.cc')
    this_env.Program(source=src,target='#/bin/'+prog)	

